version: 2.1
description: Orb for firebase deploy.
jobs:
  deploy:
    description: Deploy to firebase
    docker: 
      - image: circleci/node:8.16.0
    steps:
      - run:
          name: Install
          command: ls && npm ci
      - run:
          name: Deploy to Firebase
          command: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy