version: 2.1
description: Orb for firebase deploy.
commands:
  deploy:
    description: Deploy to firebase
    parameters:
      token:
        type: string
        description: Firebase Deploy Token
    steps:
      - run:
          name: Install
          command: npm ci
      - run:
          name: Deploy to Firebase
          command: npm run deploy -- --token=<< parameters.token >>